### ISSUE TITLE
Devel Docs: Charm Generate Process Not Found

### ISSUE THREAD

**Issue by arosales** [juju/docs#838] opened 2016-01-28 10:55 UTC
I wasn't able to easily find the "charm generate" process. Specifically the commands I should run to build my charm, inspect my charm, review a generated charm.

Also the following links are 404:
https://jujucharms.com/docs/devel/developers-layers-interfaces/
https://jujucharms.com/docs/devel/developer-debugging-layers/

**Comment by ns950** [comment] 2016-02-07 03:29
I fixed the broken URls and the first has already been pulled, the second pending. Not yet addressed the first point here.

**Comment by marcoceppi** [comment] 2016-02-07 14:07
It should also be noted that `charm generate` is now `charm build`

**Comment by mbruzek** [comment] 2016-06-28 16:31
@arosales This appears to be a duplicate of #913 which I fixed in #1212.

The first link is not developer**s** but developer.

Also the last link changed to https://jujucharms.com/docs/devel/developer-debug-layers so it looks like "ing" was removed.

**Closed** 2016-06-28 16:50 UTC
Labels: duplicate
