### ISSUE TITLE
Clarify bootstrap confusion regarding proxies and Juju GUI

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1690] opened 2017-03-01 21:56 UTC
From IRC and @anastasiamac.

There was some talk yesterday on one of the Juju channels about people being stuck downloading the Juju GUI during bootstram. People were asking why Juju does not pick up the proxy they are using. It seems there is some confusion over where the different parts exist, especially wrt the GUI being downloaded to the client, so it wouldn't be affected by the proxy config that is passed to bootstrap, but only by any proxy settings that exist in the shell where the command was run.

This looks like a good candidate for an expanded explanation somewhere appropriate in the bootstrap documentation, perhaps a quick note explaining what happens at bootstrap and which things happen locally and which happen remotely.

**Comment by matthewhelmke** [comment] 2017-03-01 22:08
This will need to be massaged a bit, especially since my reading of [The Juju GUI](https://jujucharms.com/docs/stable/controllers-gui) is that the Juju GUI is a charm that is deployed to the controller and accessed via a browser. So, some research is required for clarification before writing anything.

**Comment by matthewhelmke** [comment] 2017-03-01 22:36
Ref: [https://bugs.launchpad.net/juju/+bug/1669155](https://bugs.launchpad.net/juju/+bug/1669155)

**Comment by evilnick** [comment] 2017-03-03 12:41
I think we want to be really careful about adding extra complexity to the docs for handling an edge case scenario which Juju itself has the opportunity to warn users about.

**Comment by matthewhelmke** [comment] 2017-03-03 12:44
I agree. I do think we should watch to see how the LP bug is resolved before moving ahead, and once we have more info, then the path will be clearer. As it is, the current docs and what I think I understand from the original report here seem to imply something is incorrect, either the understanding in the report or the docs.

**Comment by evilnick** [comment] 2017-03-03 12:52
Yes. Perhaps I am misunderstanding something. The issue is that apparently the GUI is installed through the client and not fetched directly from the controller? I don't find these 'add clarity to the docs' bugs which don't actually contain the clarity which we need to add, to be helpful.
It does seem reasonable to me though that Juju itself, since it always installs the GUI, is in a rather excellent position to know if it is a) using proxies and b) can't fetch the GUI charm could provide some helpful error messaging. Knowing exactly what is happening is useful to users in general when there is a problem - when things work as expected they most likely don't care

**Comment by pmatulis** [comment] 2017-09-20 18:36
@evilnick Please advise if you want me to add to [controllers-creating](https://github.com/juju/docs/blob/master/src/en/controllers-creating.md), otherwise, let's just close this one.

## Creating a controller
...
### Juju GUI
A web interface is, by default, installed within every controller. See [Juju GUI] for an in-depth coverage of the GUI.

!!! Note:
The GUI is installed by first being downloaded within the Juju client environment. Therefore, any environmental variables set in the client's shell may affect this download, proxy variables in particular.

### Constraints
...

**Comment by evilnick** [comment] 2017-09-21 09:18
@pmatulis No, I don't want to clutter up that page for the reasons outlined above. It seems to me that this is an issue Juju itself should address. We could possibly clarify where the GUI comes from on the GUI page.

**Comment by pmatulis** [comment] 2017-09-21 13:05
I put it on the **controllers-creating** page because doing so gave the opportunity to inform what else you get when you **create** a controller (i.e. the GUI).

The [GUI page](https://github.com/juju/docs/blob/master/src/en/controllers-gui.md) already states (at the very top):

> [,..] unless you bootstrap your controller with the --no-gui option, the GUI is automatically embedded within every Juju controller.

So shall we just close this?

**Comment by evilnick** [comment] 2017-09-21 17:14
There is too much stuff on that page already. If you want you can add an example of creating a controller **without** the GUI, and possibly linking to the GUI page.

There is no point in belabouring information that the users do not need to know or care about 99.99% of the time, it just makes the documentation worse.

**Closed by evilnick** 2017-09-21 17:14 UTC
Labels: blocked
