### ISSUE TITLE
docs needed: upgrade-juju command and general upgrade procedure

### ISSUE THREAD

**Issue by evilnick** [juju/docs#89] opened 2014-05-01 18:16 UTC

**Comment by petermatulis** [comment] 2015-07-30 16:26
@marcoceppi 
What bug is this a duplicate of?

**Comment by petermatulis** [comment] 2015-08-14 14:44
I'm planning on a dedicating a new and substantial page to upgrading Juju in general, including best practices and so on.

**Comment by petermatulis** [comment] 2015-08-14 14:46
@evilnick
Take note!

**Comment by petermatulis** [comment] 2015-09-17 17:38
Fixed in PR #679 . Closing

**Closed by petermatulis** 2015-09-17 17:38 UTC
Labels: high priority
