### ISSUE TITLE
New bundle options include-file and include-base64 needs documenting

### ISSUE THREAD

**Issue by szeestraten** [juju/docs#2070] opened 2017-09-08 10:37 UTC
Juju PR - juju/juju#7825, see also https://github.com/juju/docs/blob/717709f52e4d5e425b573a1f0e0c3c65a11dbd64/src/en/reference-release-notes.md#new-and-improved

**Comment by pmatulis** [comment] 2017-09-08 14:56
This is a duplicate of #2069. Closing.

**Closed by pmatulis** 2017-09-08 14:56 UTC
Labels: duplicate

**Comment by kcd83** [comment] 2018-02-05 02:02
This is done? there is no mention of `include-base64` I can find looking at https://jujucharms.com/docs/devel/charms-bundles or https://github.com/juju/docs/pull/1891/files

**Comment by szeestraten-ntnu** [comment] 2018-02-05 10:04
@kcd83 It was done in #2088. You can find it here: https://github.com/juju/docs/blob/master/src/en/charms-bundles.md#setting-charm-configurations-options-in-a-bundle

**Comment by pmatulis** [comment] 2018-02-05 14:21
@kcd83 Agreed?

**Comment by kcd83** [comment] 2018-02-06 03:30
Ah yes. It is there

>>> Values for options and annotations can also be read from a file. For binary files, such as binary certificates, there is an option to base64-encode the contents. A file location can be expressed with an absolute or relative (to the bundle file) path.

Thanks
