### ISSUE TITLE
Update needed: GCE provider

### ISSUE THREAD

**Issue by mitechie** [juju/docs#747] opened 2015-11-26 01:44 UTC
Copied from: https://github.com/CanonicalLtd/jujucharms.com/issues/185 per @loslosbaby

This page: https://jujucharms.com/docs/stable/config-gce

...is great, but there are issues:
- the screen captures are out of date
- the JSON for the OAuth has tags that have to be deleted before juju bootstrap will work

juju bootstrap fails with:
Bootstrap failed, cleaning up the environment.
ERROR there was an issue examining the environment: invalid config: key "auth_uri" not supported

The tags that have to be deleted are:
- auth_uri
- token_uri
- auth_provider_x509_cert_url
- client_x509_cert_url

Alternately, juju can be modified to ignore the tags.  I'll let you decide if a bug needs to be filed.

**Comment by evilnick** [comment] 2015-11-26 13:38
Hi @loslosbaby, thanks for the report

Yeah, sadly the GCE page changes quite a lot, but we will update the images. I am more concerned about the keys needing to be changed. Just to clarify, this is when you use the option of specifying the downloaded JSON with 

auth-file: /home/juju-user/.juju/Juju-GCE-7e04ea455a2d.json

or similar?

**Comment by sheepeatingtaz** [comment] 2015-12-30 16:00
I can confirm this. As well as the items listed above, I also had to remove "project_id" from the json when using the auth-file option.

**Comment by chuckbutler** [comment] 2016-01-13 17:40
Couple things here:

When i added the GCE provider and created a service account, the juju GCE provider forced me to remove ~ 6 keys from my config.json. This is problematic. 

I feel that the juju config scanner should only care that we have the 4 required keys, the rest should simply be ignored.

The error messaging around this could be more helpful too:

`ERROR there was an issue examining the environment: invalid config: key "auth_uri" not supported`
`ERROR there was an issue examining the environment: invalid config: key "project_id" not supported`

This was the output from 1.26-alpha3-trusty-amd64

**Comment by evilnick** [comment] 2016-01-14 07:11
I agree that it is a problem that should be fixed in juju rather than in docs.
However, I know a lot of this will be changing in 2.0, so I expect it is easier to document workarounds for now until the problem solves itself.

**Comment by petermatulis** [comment] 2016-01-21 21:13
Comment ( @tych0 ) from duplicate #811 

===
referring to: https://jujucharms.com/docs/1.25/config-gce

The screenshots for where to click and such are off, since google has (yet again, I'm sure :) changed the interface. You need to create a "Service Account" instead of just an Oauth 2.0 Client account as it says; only a service account gets the private key that juju understands.

Once you have the service account json, you need to go through and change all the _s in the key name to -s, e.g. sed -i 's/project_id/project-id' foo.json (and for everything else as well) if you want to pass juju the filepath. Alternatively, copying the values from the json into your environments.yaml still seems to work just fine.

**Comment by evilnick** [comment] 2016-01-22 08:44
thanks @tych0, yeah the google monkeys have changed the way their site works and where to find everything at least 4 times now, but thanks for the clarifications - we are patching this for now and hoping it will last until 2.0

**Comment by petermatulis** [comment] 2016-01-27 19:09
@evilnick 
I propose we provide just one way, the simpler way, to configure. This is pointing to the downloaded file in `environments.yaml`. Agreed?

**Comment by evilnick** [comment] 2016-01-27 20:12
I'm not sure that is the simpler way. Currently the downloaded file has to be edited to rename, and in some cases remove parts which Juju doesn't understand> I think if we do one way, it should be manually putting the values into the yaml, which you can get from the console or downloading the json file. This gives users the best chance of finding the correct information, even if things change again.

**Comment by petermatulis** [comment] 2016-01-28 13:47
I can confirm that (with `2.0-alpha1-0ubuntu1~15.10.1~juju1`) when using the pointing method (auth-file) the following parts need to be removed from the auth file:

 * project-id
 * auth-uri
 * token_uri
 * auth_provider_x509_cert_url
 * client-x509-cert-url

Doing s/_/-/ seems to help at first but ultimately the modified keys are rejected. The above keys are the unmodified (original) versions.

**Comment by evilnick** [comment] 2016-01-28 14:07
yes, so I think manual input is, in some ways, easier

**Comment by axw** [comment] 2016-02-01 03:22
@petermatulis @evilnick FYI, I have fixed the GCE provider code in the cloud-credentials feature branch. You will be able to use the downloaded JSON file without any modification in Juju 2.0. This needs to be fixed in Juju 1.25.x as well, I just haven't gotten to it.

**Comment by petermatulis** [comment] 2016-02-01 19:05
Closing. Merged #841 and backported to 1.24 and 1.25.

**Closed by petermatulis** 2016-02-01 19:05 UTC
Labels: high priority, in progress, please backport

**Comment by tych0** [comment] 2016-02-01 19:49
Thanks guys!
