### ISSUE TITLE
Troubleshooting docs need a starting point

### ISSUE THREAD

**Issue by mattyw** [juju/docs#842] opened 2016-02-01 15:10 UTC
The link to juju troubleshooting says "coming soon"
https://jujucharms.com/docs/devel/troubleshooting

I'd suggest as an interim we use this post from @castrojo 's blog

http://www.jorgecastro.org/2014/05/29/real-world-juju-troubleshooting/

**Comment by evilnick** [comment] 2016-02-01 16:06
dupe of #833

**Closed by evilnick** 2016-02-01 16:06 UTC

**Comment by mattyw** [comment] 2016-02-01 16:21
@evilnick not sure I'm happy about it just being marked as dup. #833 is just observations about the page in general. I'm stating something specific we can do to fix one of the links
